spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        format_sql: true
          default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create

logging.level:
  org.hibernate.SQL: debug
